### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by dg482** [signes-pl/laravel-acl#14]
FatalErrorException in Acl.php line 8:
Cannot use Signes\Acl\Contract\UserInterface as UserInterface because the name is already in use

![643013fbb8](https://cloud.githubusercontent.com/assets/1058411/21499289/5716bfa4-cc56-11e6-9094-1fb7f0b8bad5.jpg)

Sorry for my English, the error is caused when you try to play an example.
When you install the package through the composer was a mistake.

**Comment by pgrzesiecki** [comment]
Correct interface is `Signes\Acl\Contract\UserInterface`.
There is no class `Signes\Acl\UserINterface` in repository.

Sorry for my late response.
