### ISSUE TITLE
Can't install it via composer to L5 project

### ISSUE THREAD

**Issue by userVF** [signes-pl/laravel-acl#6]
Hello  szarik88! This package is what i need,
but when "composer update" is performed  the error occurs:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install laravel/framework v5.0.15
    - Conclusion: remove laravel/framework v5.0.14
    - Conclusion: don't install laravel/framework v5.0.14
    - Conclusion: don't install laravel/framework v5.0.13
    - Conclusion: don't install laravel/framework v5.0.12
    - Conclusion: don't install laravel/framework v5.0.11
    - Conclusion: don't install laravel/framework v5.0.10
    - Conclusion: don't install laravel/framework v5.0.9
    - Conclusion: don't install laravel/framework v5.0.8
    - Conclusion: don't install laravel/framework v5.0.7
    - Conclusion: don't install laravel/framework v5.0.6
    - Conclusion: don't install laravel/framework v5.0.5
    - Conclusion: don't install laravel/framework v5.0.4
    - Conclusion: don't install laravel/framework v5.0.3
    - Installation request for signes/acl dev-master -> satisfiable by signes/acl[dev-master].
    - Conclusion: don't install laravel/framework v5.0.2
    - Conclusion: don't install laravel/framework v5.0.1
    - signes/acl dev-master requires illuminate/support 4.2.* -> satisfiable by illuminate/support[v4.2.1, v4.2.12, v4.2.16, v4.2.17, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9].
    - don't install illuminate/support v4.2.1|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.2.12|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.2.16|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.2.17|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.2.2|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.2.3|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.2.4|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.2.5|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.2.6|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.2.7|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.2.8|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.2.9|don't install laravel/framework v5.0.0
    - Installation request for laravel/framework 5.0.* -> satisfiable by laravel/framework[v5.0.0, v5.0.1, v5.0.10, v5.0.11, v5.0.12, v5.0.13, v5.0.14, v5.0.15, v5.0.2, v5.0.3, v5.0.4, v5.0.5, v5.0.6, v5.0.7, v5.0.8, v5.0.9].

My require section in composer.json:

"require": {
		"laravel/framework": "5.0.*",
		"signes/acl": "dev-master"
	},

I found here http://packalyst.com/packages/package/signes/acl that Required: Laravel >= 4.2
My version is 5.0.14. 
Maybe I'm not well familiar with a composer work.
Please could you help me with this issue?
Thanx.

**Comment by szarik88** [comment]
Hello,
Unfortunately Laravel 5 is not yet supported. 
I'll do my best to update this package to Laravel 5 as soon as possible.

**Comment by userVF** [comment]
It would be very well!

**Comment by szarik88** [comment]
Thanks you for your patience.
You can try new version, which is compatible with Laravel 5.
Try code from [Laravel5](https://github.com/signes-pl/laravel-acl/tree/laravel5) branch.

**Comment by userVF** [comment]
hi
I installed the package from L5 branch.
On migrate stage a few errors occurs.
1)Violating not-null constraint for "created_at/updated_at" fields during the tables populating:
acl_groups
acl_group_roles
acl_roles
acl_users
Solved (for PostgreSQL): 
//$table->timestamps();
$table->timestamp('created_at')->default(DB::raw('now()::timestamp(0)'));
$table->timestamp('updated_at')->default(DB::raw('now()::timestamp(0)'));

2)Violating not-null constraint for "remember_token" during the acl_users are populating.
Solved:
$table->string('remember_token', 150)->nullable();

That's my quick solutions to continue the package testing.

**Comment by szarik88** [comment]
Feel free to add pull request.
I'll check this problem as soon as possible. On MySQL there is no problem with types. Probably, as you describe, it is only on PostgreSQL.
