### ISSUE TITLE
Can't install it via composer to L5.1.x project

### ISSUE THREAD

**Issue by bruceslan1989** [signes-pl/laravel-acl#7]

**Comment by Dexberry** [comment]
am also Trying to install to Laravel 5.1 :( i hope we can see updates asap

**Comment by szarik88** [comment]
Laravel 5.1 is supported since version 2.1 of this package. Please update your code and test.
Thanks for feedback.

**Comment by Dexberry** [comment]
Thank you so much :100:  it's done
